import { BasciConnect } from "components/ConnectWallet";
import type { NextPage } from "next";
import { Machine, assign } from 'xstate';
import { Header } from "components/Header";
import { Splash } from "components/Splash";

import Head from "next/head";
import { useState } from "react";
const Home: NextPage = () => {
    const [yaml, setYaml] = useState('');

    return (
       
        <div>            <Splash></Splash>

            <Header> 
</Header>
            <Head>
                <title>Anonymous Web Services Rogue Node Command Center</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <footer className="footer">
      <a href="https://github.com/">
        <img src="https://www.zap.org/static/discord.svg" alt="GitHub icon" />
      </a>
      <a href="https://twitter.com/">
        <img src="https://www.zap.org/static/twitter.svg"alt="Twitter icon" />
      </a>
      <a href="https://linkedin.com/">
        <img src="https://www.zap.org/static/linkedin.svg" alt="LinkedIn icon" />
      </a>
      <a href="https://uniswap.org/">
        <img src="https://www.zap.org/static/instagram.svg" alt="Uniswap icon" />
      </a>
    </footer>
  </div>
    );
};

export default Home;
